class ShortStraddleState:
    STRADDLE_STARTED = "STRADDLE_STARTED"
    ENTRY_ORDER_PLACED = "ENTRY_ORDER_PLACED"
    SL_ORDER_PLACED = "SL_ORDER_PLACED"
    TARGET_HIT = "TARGET_HIT"
    CE_SL_HIT = "CE_SL_HIT"
    PE_SL_HIT = "PE_SL_HIT"
    BOTH_SL_HIT = "BOTH_SL_HIT"
    COMPLETED = "COMPLETED"